apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: foodapi
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: foodapi
  endpoints:
    - port: http
      path: {{ .Values.metrics.path }}
      interval: 15s
