apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: foodapi
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ogash3103/agri-observability-demo.git
    targetRevision: main
    path: charts/foodapi
  destination:
    server: https://kubernetes.default.svc
    namespace: agri
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
