name: foodapi-ci-cd

on:
  push:
    branches: [ "main" ]
    paths:
      - "src/FoodApi/**"
      - "charts/foodapi/**"

jobs:
  build-push-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set tag
        id: vars
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/foodapi:${{ steps.vars.outputs.TAG }} \
            -f src/FoodApi/FoodApi/Dockerfile \
            .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/foodapi:${{ steps.vars.outputs.TAG }}

      - name: Update Helm values image tag
        run: |
          sed -i "s/tag: \".*\"/tag: \"${{ steps.vars.outputs.TAG }}\"/g" charts/foodapi/values.yaml
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add charts/foodapi/values.yaml
          git commit -m "chore: bump foodapi image tag to ${{ steps.vars.outputs.TAG }}" || exit 0
          git push
